import {dataInterface} from './types'
const Menu:dataInterface[] = [
  {
    id: 1,
    title: 'buttermilk pancakes',
    category: 'breakfast',
    price: 15.99,
    img: './images/breakfast3.jpeg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: 'diner double',
    category: 'lunch',
    price: 13.99,
    img: './images/lunch1.jpeg',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'shakes',
    price: 6.99,
    img: './images/shake1.jpeg',
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
id: 4,
    title: 'Dinner special',
    category: 'dinner',
    price: 6.99,
    img: './images/dinner1.jpeg',
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`
  },
  {
    id: 5,
    title: 'country delight',
    category: 'breakfast',
    price: 20.99,
    img: './images/breakfast2.jpeg',
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 6,
    title: 'egg attack',
    category: 'lunch',
    price: 22.99,
    img: './images/lunch2.jpeg',
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 7,
    title: 'oreo dream',
    category: 'shakes',
    price: 18.99,
    img: './images/shake2.jpeg',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 8,
    title: 'strawberry ice cream',
    category: 'icecream',
    price: 18.99,
    img: './images/icecream1.jpeg',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 9,
    title: 'Blue Moon ice cream',
    category: 'icecream',
    price: 18.99,
    img: './images/icecream2.jpeg',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 10,
    title: 'bacon overflow',
    category: 'breakfast',
    price: 8.99,
    img: './images/breakfast4.jpeg',
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 18,
    title: 'american classic',
    category: 'lunch',
    price: 12.99,
    img: './images/lunch3.jpeg',
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 11,
    title: 'quarantine buddy',
    category: 'shakes',
    price: 16.99,
    img: './images/shake3.jpeg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 12,
    title: "pav bhaji",
    category: "mumbai's spl",
    price: 49.99,
    img: './images/mumspl1.jpeg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 13,
    title: "vada pav",
    category: "mumbai's spl",
    price: 10.99,
    img: './images/mumspl2.jpeg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 14,
    title: "Bruschetta",
    category: 'dinner',
    price: 306.99,
    img: './images/dinner2.jpeg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 15,
    title: "Samosa",
    category: "mumbai's spl",
    price: 49.99,
    img: './images/mumspl3.jpeg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 16,
    title: "Mahathali",
    category: "mumbai's spl",
    price: 99.99,
    img: './images/mumspl5.jpeg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
   {
    id: 17,
    title: 'bagel',
    category: 'breakfast',
    price: 15.99,
    img: './images/breakfast1(bagel).jpeg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
];
export {Menu};